mytestkey=This value is from LOCAL properties file

merchant.username=merchant_username
merchant.password=merchant_password
notification.url=https://URL_to_your_notification_service/dajskldjakls123
trustly.deposit.url=http://localhost:8085/payment/initiate

# ========= Eureka Client Configuration =========
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

